FROM ubuntu:20.04

WORKDIR /aib-l4t5


RUN apt-get update && apt-get install --no-install-recommends -y \
	wget lbzip2 build-essential bc zip libgmp-dev libmpfr-dev libmpc-dev vim-common 


CMD ["/bin/bash"] 